In [21]:
import numpy as np

In [22]:
A = np.array([[0, 1], [2, 3], [4, 5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
B = np.array([[0,1,2,3], [4,5,6,7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
B2 = np.arange(8).reshape(2, 4)
B2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
C = np.dot(A, B)
C

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [26]:
max = C.max()
max

47